### ISSUE TITLE
Enable Github Actions for this repository

### ISSUE THREAD

**Issue by timflannagan** [operate-first/curator-operator#3]
This repository currently has a somewhat fleshed out CI pipeline that uses Github Actions to handle our CI (and potential CD) needs. It sounds like the operator-first organization has support for GHAs but we need to enable for this repository.

**Comment by timflannagan** [comment]
Just tracking this here after our conversation earlier so we have an audit. cc @gagansk

**Comment by gagansk** [comment]
@HumairAK Can you help us to Enable GitHub Actions?

**Comment by HumairAK** [comment]
done

**Comment by timflannagan** [comment]
@HumairAK I tried triggering the ci.yaml CI pipeline in https://github.com/operate-first/curator-operator/pull/7 and didn't see any actions jobs start up. It looks like that workflow is targeting the correct pull_request trigger to the main branch, and I don't see the `Actions` tab in the github UI like I typically do on repositories I contribute to regularly. Any idea on what's happening here?

**Comment by HumairAK** [comment]
bah I accidentally did it for the curator respository, this repository should now have actions enabled, sorry about that!

**Comment by timflannagan** [comment]
@HumairAK all good - thanks for the help (as always)!

/close
