### ISSUE TITLE
Introduce a root OWNERS file

### ISSUE THREAD

**Issue by timflannagan** [operate-first/curator-operator#4]
This repository appears to use tide it's merging tool which requires a root OWNERS file to apply the requisite lgtm/approved labels as we don't have explicit merging access enabled for this repository.

AC:

- Add a root OWNERS file that has a `reviewers:` field with everyone on the team listed and a `approvers:` field for people that have access to approve PRs.

Sample root OWNERS file that can be used as a reference: https://github.com/operator-framework/rukpak/blob/main/OWNERS.

**Comment by timflannagan** [comment]
Probably easiest to just have me and @gagansk set as approvers for now?

**Comment by gagansk** [comment]
@timflannagan Yes. Sounds good
