### ISSUE TITLE
Rename the "test" Makefile target to "test-unit"

### ISSUE THREAD

**Issue by timflannagan** [operate-first/curator-operator#46]
Goal: rename the "test" Makefile and rename it to "test-unit" so we can run the unit and [e2e suite](#19) in separate instances.

AC:
- Update the Makefile and rename the "test" target to "test-unit".
- Update any references to that previous "test" target (github action workflows, .PHONY targets in the Makefile, etc.)

**Comment by ajinkyababar** [comment]
Close #58
