### ISSUE TITLE
Intern on-boarding: Create a documentation to present the understanding of curator.

### ISSUE THREAD

**Issue by AvRajath** [operate-first/curator-operator#54]
Deliverables:

- Create ~2 page document explaining the understanding of curator project.

Due: 06/01/2022

**Comment by AvRajath** [comment]
Sharing the first draft of the document Project [Curator-operator](https://docs.google.com/document/d/1yLoztJTn-kn5SIn4s755rpzwkedF7DQSGF0jFt2c49Q/edit?usp=sharing).

**Comment by gagansk** [comment]
Looks good. Thanks @AvRajath

**Comment by AvRajath** [comment]
@hpdempsey Updated the document with all the suggested changes. Please let me know if there are any more changes. I shall talk to @gagansk regarding adding that image to the research.redhat.com page.
