### ISSUE TITLE
Add avrajath to the curator project on Github

### ISSUE THREAD

**Issue by AvRajath** [operate-first/curator-operator#55]
@gagansk Requesting you to add @avrajath to the curator project Github repo so that I can have access to modify the issues.

**Comment by gagansk** [comment]
A PR has been raised in the Operate First GitHub organization.

https://github.com/operate-first/common/pull/114

**Comment by gagansk** [comment]
https://github.com/operate-first/common/pull/114 is merged and closed. 

Closing this issue.
