### ISSUE TITLE
OpenCost competitor analysis

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator-operator#60]
Kubecost is developing OpenCost that might be similar to what Curator does. Research the OpenCost specs and their agenda. 

https://github.com/kubecost/opencost/blob/develop/spec/opencost-specv01.md

DoD:
* Prepare a document identifying feature gaps, and work hours required.
* Present the findings to the Cost Mgmt PM team.

**Comment by ajinkyababar** [comment]
[Feature Gap Analysis](https://docs.google.com/document/d/11vcP0LxMI0swgkneFyFpP99S_ti1cqpEYRKDp_UIJI8/edit)
